language: python
python:
    - "2.7"
install:
    - pip install --upgrade tox
before_script:
    - export AWS_DEFAULT_REGION=us-east-1
    - export AWS_SECRET_ACCESS_KEY=none
    - export AWS_ACCESS_KEY_ID=none
script:
    - tox -r
after_success:
    - coveralls
