language: python
python:
    - "2.7"
install:
    - pip install -rrequirements.txt
    - pip install -rtest-requirements.txt
    - python setup.py install
script:
    - nosetests --with-coverage -v --cover-package fmc
after_success:
    - coveralls
